const Images = {
  home: require('../assets/images/drawer/home.png'),
  createsalesorder: require('../assets/images/drawer/createorder.png'),
  claimlist: require('../assets/images/drawer/claimlist.png'),
  warrantylist: require('../assets/images/drawer/warrantylist.png'),
  salesorderlist: require('../assets/images/drawer/salesorder.png'),
  accountsummary: require('../assets/images/drawer/accountsummary.png'),
  creditdebitnotes: require('../assets/images/drawer/creditdebitnotes.png'),
  purchasesummary: require('../assets/images/drawer/purchasesummary.png'),
  newwarrenty: require('../assets/images/drawer/newwarrenty.png'),
  newcliam: require('../assets/images/drawer/newclaim.png'),
  pointsummary: require('../assets/images/drawer/points.png'),
  Requests: require('../assets/images/drawer/faq.png'),
  securitydeposit: require('../assets/images/drawer/securitydeposit.png'),
  tdstcscertificate: require('../assets/images/drawer/tdstcscertificate.png'),
  ycnargreement: require('../assets/images/drawer/ycnagreement.png'),
  survey: require('../assets/images/drawer/survey.png'),
  creditlimitproposal: require('../assets/images/drawer/creditlimit.png'),
  lead: require('../assets/images/drawer/lead.png'),
  ycnmerchandise: require('../assets/images/drawer/ycnmerchant.png'),
  ycnorderlist: require('../assets/images/drawer/ycnorderlist.png'),
  creditsummary: require('../assets/images/drawer/creditsummary.png'),
  agesummary: require('../assets/images/drawer/ageingsummary.png'),
  claimdispatchconfirmation: require('../assets/images/drawer/claimdispatch.png'),
  contactus: require('../assets/images/drawer/contactus.png'),
  makepayment: require('../assets/images/drawer/makepayment.png'),
  productpolicy: require('../assets/images/drawer/productpolicy.png'),
  warrentypolicy: require('../assets/images/drawer/warrentypolicy.png'),
  faq: require('../assets/images/drawer/faq.png'),
  security: require('../assets/images/drawer/security.png'),
  about: require('../assets/images/drawer/about.png'),
  instagram: require('../assets/images/social/instagram.png'),
  facebook: require('../assets/images/social/facebook.png'),
  twitter: require('../assets/images/social/twitter.png'),
  youtube: require('../assets/images/social/youtube.png'),
  arrow_right: require('../assets/images/arrows/arrowright.png'),
  check: require('../assets/images/common/check.png'),
  back: require('../assets/images/common/back.png'),
  gallery: require('../assets/images/common/gallery.png'),
  downarrow: require('../assets/images/arrows/downarrow.png'),
  add: require('../assets/images/common/add.png'),
  tick: require('../assets/images/common/tick.png'),
  shoppingcart: require('../assets/images/common/shoppingcart.png'),
  newcart: require('../assets/images/common/newcart.png'),
  greentick: require('../assets/images/common/greentick.png'),
  reset: require('../assets/images/common/reset.png'),
  ticket: require('../assets/images/menu/ticket.png'),
  linkedin: require('../assets/images/common/linkedin.png'),
  OffersMYK: require('../assets/images/OffersMYK.png'),

};

export default Images;
