const authActions = {
  OPEN_SETTINGS: 'OPEN_SETTINGS',
  SET_IS_VERIFIED: 'SET_IS_VERIFIED',
  SET_USER_DATA: 'SET_USER_DATA',
  SET_IS_INITIALIZED: 'SET_IS_INITIALIZED',
  SET_TOKENS: 'SET_TOKENS',
  SET_INVOICEDATA: 'SET_INVOICEDATA',
  LOG_OUT: 'LOG_OUT',
  SET_CURRENT_LOCATION: 'SET_CURRENT_LOCATION',
  SET_LOCATION: 'SET_LOCATION',
  UPDATED_TOKEN: 'UPDATED_TOKEN',
  SET_APP_CURRENT_MODE: 'SET_APP_CURRENT_MODE',
  SET_SPLASH_SCREEN_STATUS: 'SET_SPLASH_SCREEN_STATUS',
  SET_ERROR: 'SET_ERROR',
  SET_LAST_REQUEST: 'SET_LAST_REQUEST',
  SET_NO_INTERNET: 'SET_NO_INTERNET',
  SET_SOCKET_INSTANCE: 'SET_SOCKET_INSTANCE',
  SET_WELCOME: 'SET_WELCOME',
  SET_EMOJIS: 'SET_EMOJIS',
  SET_IMAGE_PERMISSION: 'SET_IMAGE_PERMISSION',
  SET_CART_DATA: 'SET_CART_DATA',
  SET_USER_ID: 'SET_USER_ID',
  SET_ICON: 'SET_ICON',
  SET_YCN_CART_DATA: 'SET_YCN_CART_DATA',
  SET_QR_DATA: "SET_QR_DATA",
  PRODUCT_SEARCH: "PRODUCT_SEARCH",
  SET_AVAILABLE_CREDIT_LIMIT: "SET_AVAILABLE_CREDIT_LIMIT",
  SET_PDF_LOADING: "SET_PDF_LOADING",
  
  SET_ORDER_DATA:'SET_ORDER_DATA'
};

export default authActions;
